/*
 * This file is generated by jOOQ.
 */
package cn.sl.manager.database.tables;


import cn.sl.manager.database.Keys;
import cn.sl.manager.database.Sl;
import cn.sl.manager.database.tables.records.BerthRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Berth extends TableImpl<BerthRecord> {

    private static final long serialVersionUID = 518526436;

    /**
     * The reference instance of <code>sl.berth</code>
     */
    public static final Berth BERTH = new Berth();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BerthRecord> getRecordType() {
        return BerthRecord.class;
    }

    /**
     * The column <code>sl.berth.id</code>.
     */
    public final TableField<BerthRecord, Integer> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>sl.berth.name</code>.
     */
    public final TableField<BerthRecord, String> NAME = createField(DSL.name("name"), org.jooq.impl.SQLDataType.VARCHAR(32).nullable(false), this, "");

    /**
     * The column <code>sl.berth.created_at</code>.
     */
    public final TableField<BerthRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), org.jooq.impl.SQLDataType.LOCALDATETIME, this, "");

    /**
     * The column <code>sl.berth.deleted</code>.
     */
    public final TableField<BerthRecord, Boolean> DELETED = createField(DSL.name("deleted"), org.jooq.impl.SQLDataType.BIT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("b'0'", org.jooq.impl.SQLDataType.BIT)), this, "");

    /**
     * Create a <code>sl.berth</code> table reference
     */
    public Berth() {
        this(DSL.name("berth"), null);
    }

    /**
     * Create an aliased <code>sl.berth</code> table reference
     */
    public Berth(String alias) {
        this(DSL.name(alias), BERTH);
    }

    /**
     * Create an aliased <code>sl.berth</code> table reference
     */
    public Berth(Name alias) {
        this(alias, BERTH);
    }

    private Berth(Name alias, Table<BerthRecord> aliased) {
        this(alias, aliased, null);
    }

    private Berth(Name alias, Table<BerthRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> Berth(Table<O> child, ForeignKey<O, BerthRecord> key) {
        super(child, key, BERTH);
    }

    @Override
    public Schema getSchema() {
        return Sl.SL;
    }

    @Override
    public Identity<BerthRecord, Integer> getIdentity() {
        return Keys.IDENTITY_BERTH;
    }

    @Override
    public UniqueKey<BerthRecord> getPrimaryKey() {
        return Keys.KEY_BERTH_PRIMARY;
    }

    @Override
    public List<UniqueKey<BerthRecord>> getKeys() {
        return Arrays.<UniqueKey<BerthRecord>>asList(Keys.KEY_BERTH_PRIMARY);
    }

    @Override
    public Berth as(String alias) {
        return new Berth(DSL.name(alias), this);
    }

    @Override
    public Berth as(Name alias) {
        return new Berth(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Berth rename(String name) {
        return new Berth(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Berth rename(Name name) {
        return new Berth(name, null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, String, LocalDateTime, Boolean> fieldsRow() {
        return (Row4) super.fieldsRow();
    }
}
