/*
 * This file is generated by jOOQ.
 */
package cn.sl.manager.database.tables;


import cn.sl.manager.database.Keys;
import cn.sl.manager.database.Sl;
import cn.sl.manager.database.tables.records.DiscountCouponRecord;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row6;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DiscountCoupon extends TableImpl<DiscountCouponRecord> {

    private static final long serialVersionUID = 998888334;

    /**
     * The reference instance of <code>sl.discount_coupon</code>
     */
    public static final DiscountCoupon DISCOUNT_COUPON = new DiscountCoupon();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DiscountCouponRecord> getRecordType() {
        return DiscountCouponRecord.class;
    }

    /**
     * The column <code>sl.discount_coupon.id</code>.
     */
    public final TableField<DiscountCouponRecord, Integer> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>sl.discount_coupon.code</code>. 优惠券code
     */
    public final TableField<DiscountCouponRecord, String> CODE = createField(DSL.name("code"), org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "优惠券code");

    /**
     * The column <code>sl.discount_coupon.used</code>.
     */
    public final TableField<DiscountCouponRecord, Boolean> USED = createField(DSL.name("used"), org.jooq.impl.SQLDataType.BIT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("b'0'", org.jooq.impl.SQLDataType.BIT)), this, "");

    /**
     * The column <code>sl.discount_coupon.create_at</code>.
     */
    public final TableField<DiscountCouponRecord, LocalDateTime> CREATE_AT = createField(DSL.name("create_at"), org.jooq.impl.SQLDataType.LOCALDATETIME, this, "");

    /**
     * The column <code>sl.discount_coupon.user_id</code>. 用户id
     */
    public final TableField<DiscountCouponRecord, Integer> USER_ID = createField(DSL.name("user_id"), org.jooq.impl.SQLDataType.INTEGER, this, "用户id");

    /**
     * The column <code>sl.discount_coupon.fee</code>.
     */
    public final TableField<DiscountCouponRecord, BigDecimal> FEE = createField(DSL.name("fee"), org.jooq.impl.SQLDataType.DECIMAL(10, 2).nullable(false).defaultValue(org.jooq.impl.DSL.inline("0.00", org.jooq.impl.SQLDataType.DECIMAL)), this, "");

    /**
     * Create a <code>sl.discount_coupon</code> table reference
     */
    public DiscountCoupon() {
        this(DSL.name("discount_coupon"), null);
    }

    /**
     * Create an aliased <code>sl.discount_coupon</code> table reference
     */
    public DiscountCoupon(String alias) {
        this(DSL.name(alias), DISCOUNT_COUPON);
    }

    /**
     * Create an aliased <code>sl.discount_coupon</code> table reference
     */
    public DiscountCoupon(Name alias) {
        this(alias, DISCOUNT_COUPON);
    }

    private DiscountCoupon(Name alias, Table<DiscountCouponRecord> aliased) {
        this(alias, aliased, null);
    }

    private DiscountCoupon(Name alias, Table<DiscountCouponRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> DiscountCoupon(Table<O> child, ForeignKey<O, DiscountCouponRecord> key) {
        super(child, key, DISCOUNT_COUPON);
    }

    @Override
    public Schema getSchema() {
        return Sl.SL;
    }

    @Override
    public Identity<DiscountCouponRecord, Integer> getIdentity() {
        return Keys.IDENTITY_DISCOUNT_COUPON;
    }

    @Override
    public UniqueKey<DiscountCouponRecord> getPrimaryKey() {
        return Keys.KEY_DISCOUNT_COUPON_PRIMARY;
    }

    @Override
    public List<UniqueKey<DiscountCouponRecord>> getKeys() {
        return Arrays.<UniqueKey<DiscountCouponRecord>>asList(Keys.KEY_DISCOUNT_COUPON_PRIMARY);
    }

    @Override
    public DiscountCoupon as(String alias) {
        return new DiscountCoupon(DSL.name(alias), this);
    }

    @Override
    public DiscountCoupon as(Name alias) {
        return new DiscountCoupon(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public DiscountCoupon rename(String name) {
        return new DiscountCoupon(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DiscountCoupon rename(Name name) {
        return new DiscountCoupon(name, null);
    }

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, String, Boolean, LocalDateTime, Integer, BigDecimal> fieldsRow() {
        return (Row6) super.fieldsRow();
    }
}
