/*
 * This file is generated by jOOQ.
 */
package cn.sl.manager.database.tables.records;


import cn.sl.manager.database.tables.DiscountCoupon;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DiscountCouponRecord extends UpdatableRecordImpl<DiscountCouponRecord> implements Record6<Integer, String, Boolean, LocalDateTime, Integer, BigDecimal> {

    private static final long serialVersionUID = -553023488;

    /**
     * Setter for <code>sl.discount_coupon.id</code>.
     */
    public DiscountCouponRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>sl.discount_coupon.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>sl.discount_coupon.code</code>. 优惠券code
     */
    public DiscountCouponRecord setCode(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>sl.discount_coupon.code</code>. 优惠券code
     */
    public String getCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>sl.discount_coupon.used</code>.
     */
    public DiscountCouponRecord setUsed(Boolean value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>sl.discount_coupon.used</code>.
     */
    public Boolean getUsed() {
        return (Boolean) get(2);
    }

    /**
     * Setter for <code>sl.discount_coupon.create_at</code>.
     */
    public DiscountCouponRecord setCreateAt(LocalDateTime value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>sl.discount_coupon.create_at</code>.
     */
    public LocalDateTime getCreateAt() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>sl.discount_coupon.user_id</code>. 用户id
     */
    public DiscountCouponRecord setUserId(Integer value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>sl.discount_coupon.user_id</code>. 用户id
     */
    public Integer getUserId() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>sl.discount_coupon.fee</code>.
     */
    public DiscountCouponRecord setFee(BigDecimal value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>sl.discount_coupon.fee</code>.
     */
    public BigDecimal getFee() {
        return (BigDecimal) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, String, Boolean, LocalDateTime, Integer, BigDecimal> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Integer, String, Boolean, LocalDateTime, Integer, BigDecimal> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return DiscountCoupon.DISCOUNT_COUPON.ID;
    }

    @Override
    public Field<String> field2() {
        return DiscountCoupon.DISCOUNT_COUPON.CODE;
    }

    @Override
    public Field<Boolean> field3() {
        return DiscountCoupon.DISCOUNT_COUPON.USED;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return DiscountCoupon.DISCOUNT_COUPON.CREATE_AT;
    }

    @Override
    public Field<Integer> field5() {
        return DiscountCoupon.DISCOUNT_COUPON.USER_ID;
    }

    @Override
    public Field<BigDecimal> field6() {
        return DiscountCoupon.DISCOUNT_COUPON.FEE;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getCode();
    }

    @Override
    public Boolean component3() {
        return getUsed();
    }

    @Override
    public LocalDateTime component4() {
        return getCreateAt();
    }

    @Override
    public Integer component5() {
        return getUserId();
    }

    @Override
    public BigDecimal component6() {
        return getFee();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getCode();
    }

    @Override
    public Boolean value3() {
        return getUsed();
    }

    @Override
    public LocalDateTime value4() {
        return getCreateAt();
    }

    @Override
    public Integer value5() {
        return getUserId();
    }

    @Override
    public BigDecimal value6() {
        return getFee();
    }

    @Override
    public DiscountCouponRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public DiscountCouponRecord value2(String value) {
        setCode(value);
        return this;
    }

    @Override
    public DiscountCouponRecord value3(Boolean value) {
        setUsed(value);
        return this;
    }

    @Override
    public DiscountCouponRecord value4(LocalDateTime value) {
        setCreateAt(value);
        return this;
    }

    @Override
    public DiscountCouponRecord value5(Integer value) {
        setUserId(value);
        return this;
    }

    @Override
    public DiscountCouponRecord value6(BigDecimal value) {
        setFee(value);
        return this;
    }

    @Override
    public DiscountCouponRecord values(Integer value1, String value2, Boolean value3, LocalDateTime value4, Integer value5, BigDecimal value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DiscountCouponRecord
     */
    public DiscountCouponRecord() {
        super(DiscountCoupon.DISCOUNT_COUPON);
    }

    /**
     * Create a detached, initialised DiscountCouponRecord
     */
    public DiscountCouponRecord(Integer id, String code, Boolean used, LocalDateTime createAt, Integer userId, BigDecimal fee) {
        super(DiscountCoupon.DISCOUNT_COUPON);

        set(0, id);
        set(1, code);
        set(2, used);
        set(3, createAt);
        set(4, userId);
        set(5, fee);
    }
}
