/*
 * This file is generated by jOOQ.
 */
package cn.sl.manager.database.tables.records;


import cn.sl.manager.database.tables.FinanceBook;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FinanceBookRecord extends UpdatableRecordImpl<FinanceBookRecord> implements Record12<Integer, String, LocalDateTime, LocalDateTime, Integer, Integer, Integer, BigDecimal, BigDecimal, BigDecimal, Byte, BigDecimal> {

    private static final long serialVersionUID = 1493693547;

    /**
     * Setter for <code>sl.finance_book.id</code>.
     */
    public FinanceBookRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>sl.finance_book.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>sl.finance_book.code</code>.
     */
    public FinanceBookRecord setCode(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>sl.finance_book.code</code>.
     */
    public String getCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>sl.finance_book.created_at</code>.
     */
    public FinanceBookRecord setCreatedAt(LocalDateTime value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>sl.finance_book.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>sl.finance_book.updated_at</code>.
     */
    public FinanceBookRecord setUpdatedAt(LocalDateTime value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>sl.finance_book.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>sl.finance_book.user_id</code>.
     */
    public FinanceBookRecord setUserId(Integer value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>sl.finance_book.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>sl.finance_book.company_id</code>.
     */
    public FinanceBookRecord setCompanyId(Integer value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>sl.finance_book.company_id</code>.
     */
    public Integer getCompanyId() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>sl.finance_book.goods_id</code>.
     */
    public FinanceBookRecord setGoodsId(Integer value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>sl.finance_book.goods_id</code>.
     */
    public Integer getGoodsId() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>sl.finance_book.gross_weight</code>.
     */
    public FinanceBookRecord setGrossWeight(BigDecimal value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>sl.finance_book.gross_weight</code>.
     */
    public BigDecimal getGrossWeight() {
        return (BigDecimal) get(7);
    }

    /**
     * Setter for <code>sl.finance_book.tare_weight</code>.
     */
    public FinanceBookRecord setTareWeight(BigDecimal value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>sl.finance_book.tare_weight</code>.
     */
    public BigDecimal getTareWeight() {
        return (BigDecimal) get(8);
    }

    /**
     * Setter for <code>sl.finance_book.fee</code>.
     */
    public FinanceBookRecord setFee(BigDecimal value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>sl.finance_book.fee</code>.
     */
    public BigDecimal getFee() {
        return (BigDecimal) get(9);
    }

    /**
     * Setter for <code>sl.finance_book.status</code>.
     */
    public FinanceBookRecord setStatus(Byte value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>sl.finance_book.status</code>.
     */
    public Byte getStatus() {
        return (Byte) get(10);
    }

    /**
     * Setter for <code>sl.finance_book.send_wight</code>.
     */
    public FinanceBookRecord setSendWight(BigDecimal value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>sl.finance_book.send_wight</code>.
     */
    public BigDecimal getSendWight() {
        return (BigDecimal) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row12<Integer, String, LocalDateTime, LocalDateTime, Integer, Integer, Integer, BigDecimal, BigDecimal, BigDecimal, Byte, BigDecimal> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    @Override
    public Row12<Integer, String, LocalDateTime, LocalDateTime, Integer, Integer, Integer, BigDecimal, BigDecimal, BigDecimal, Byte, BigDecimal> valuesRow() {
        return (Row12) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return FinanceBook.FINANCE_BOOK.ID;
    }

    @Override
    public Field<String> field2() {
        return FinanceBook.FINANCE_BOOK.CODE;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return FinanceBook.FINANCE_BOOK.CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return FinanceBook.FINANCE_BOOK.UPDATED_AT;
    }

    @Override
    public Field<Integer> field5() {
        return FinanceBook.FINANCE_BOOK.USER_ID;
    }

    @Override
    public Field<Integer> field6() {
        return FinanceBook.FINANCE_BOOK.COMPANY_ID;
    }

    @Override
    public Field<Integer> field7() {
        return FinanceBook.FINANCE_BOOK.GOODS_ID;
    }

    @Override
    public Field<BigDecimal> field8() {
        return FinanceBook.FINANCE_BOOK.GROSS_WEIGHT;
    }

    @Override
    public Field<BigDecimal> field9() {
        return FinanceBook.FINANCE_BOOK.TARE_WEIGHT;
    }

    @Override
    public Field<BigDecimal> field10() {
        return FinanceBook.FINANCE_BOOK.FEE;
    }

    @Override
    public Field<Byte> field11() {
        return FinanceBook.FINANCE_BOOK.STATUS;
    }

    @Override
    public Field<BigDecimal> field12() {
        return FinanceBook.FINANCE_BOOK.SEND_WIGHT;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getCode();
    }

    @Override
    public LocalDateTime component3() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime component4() {
        return getUpdatedAt();
    }

    @Override
    public Integer component5() {
        return getUserId();
    }

    @Override
    public Integer component6() {
        return getCompanyId();
    }

    @Override
    public Integer component7() {
        return getGoodsId();
    }

    @Override
    public BigDecimal component8() {
        return getGrossWeight();
    }

    @Override
    public BigDecimal component9() {
        return getTareWeight();
    }

    @Override
    public BigDecimal component10() {
        return getFee();
    }

    @Override
    public Byte component11() {
        return getStatus();
    }

    @Override
    public BigDecimal component12() {
        return getSendWight();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getCode();
    }

    @Override
    public LocalDateTime value3() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime value4() {
        return getUpdatedAt();
    }

    @Override
    public Integer value5() {
        return getUserId();
    }

    @Override
    public Integer value6() {
        return getCompanyId();
    }

    @Override
    public Integer value7() {
        return getGoodsId();
    }

    @Override
    public BigDecimal value8() {
        return getGrossWeight();
    }

    @Override
    public BigDecimal value9() {
        return getTareWeight();
    }

    @Override
    public BigDecimal value10() {
        return getFee();
    }

    @Override
    public Byte value11() {
        return getStatus();
    }

    @Override
    public BigDecimal value12() {
        return getSendWight();
    }

    @Override
    public FinanceBookRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public FinanceBookRecord value2(String value) {
        setCode(value);
        return this;
    }

    @Override
    public FinanceBookRecord value3(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public FinanceBookRecord value4(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public FinanceBookRecord value5(Integer value) {
        setUserId(value);
        return this;
    }

    @Override
    public FinanceBookRecord value6(Integer value) {
        setCompanyId(value);
        return this;
    }

    @Override
    public FinanceBookRecord value7(Integer value) {
        setGoodsId(value);
        return this;
    }

    @Override
    public FinanceBookRecord value8(BigDecimal value) {
        setGrossWeight(value);
        return this;
    }

    @Override
    public FinanceBookRecord value9(BigDecimal value) {
        setTareWeight(value);
        return this;
    }

    @Override
    public FinanceBookRecord value10(BigDecimal value) {
        setFee(value);
        return this;
    }

    @Override
    public FinanceBookRecord value11(Byte value) {
        setStatus(value);
        return this;
    }

    @Override
    public FinanceBookRecord value12(BigDecimal value) {
        setSendWight(value);
        return this;
    }

    @Override
    public FinanceBookRecord values(Integer value1, String value2, LocalDateTime value3, LocalDateTime value4, Integer value5, Integer value6, Integer value7, BigDecimal value8, BigDecimal value9, BigDecimal value10, Byte value11, BigDecimal value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FinanceBookRecord
     */
    public FinanceBookRecord() {
        super(FinanceBook.FINANCE_BOOK);
    }

    /**
     * Create a detached, initialised FinanceBookRecord
     */
    public FinanceBookRecord(Integer id, String code, LocalDateTime createdAt, LocalDateTime updatedAt, Integer userId, Integer companyId, Integer goodsId, BigDecimal grossWeight, BigDecimal tareWeight, BigDecimal fee, Byte status, BigDecimal sendWight) {
        super(FinanceBook.FINANCE_BOOK);

        set(0, id);
        set(1, code);
        set(2, createdAt);
        set(3, updatedAt);
        set(4, userId);
        set(5, companyId);
        set(6, goodsId);
        set(7, grossWeight);
        set(8, tareWeight);
        set(9, fee);
        set(10, status);
        set(11, sendWight);
    }
}
