/*
 * This file is generated by jOOQ.
 */
package cn.sl.manager.database.tables.records;


import cn.sl.manager.database.tables.Motorcade;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MotorcadeRecord extends UpdatableRecordImpl<MotorcadeRecord> implements Record5<Integer, String, Boolean, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = -1802105322;

    /**
     * Setter for <code>sl.motorcade.id</code>.
     */
    public MotorcadeRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>sl.motorcade.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>sl.motorcade.name</code>.
     */
    public MotorcadeRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>sl.motorcade.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>sl.motorcade.deleted</code>.
     */
    public MotorcadeRecord setDeleted(Boolean value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>sl.motorcade.deleted</code>.
     */
    public Boolean getDeleted() {
        return (Boolean) get(2);
    }

    /**
     * Setter for <code>sl.motorcade.created_at</code>.
     */
    public MotorcadeRecord setCreatedAt(LocalDateTime value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>sl.motorcade.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>sl.motorcade.updated_at</code>.
     */
    public MotorcadeRecord setUpdatedAt(LocalDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>sl.motorcade.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, String, Boolean, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, String, Boolean, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Motorcade.MOTORCADE.ID;
    }

    @Override
    public Field<String> field2() {
        return Motorcade.MOTORCADE.NAME;
    }

    @Override
    public Field<Boolean> field3() {
        return Motorcade.MOTORCADE.DELETED;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return Motorcade.MOTORCADE.CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return Motorcade.MOTORCADE.UPDATED_AT;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public Boolean component3() {
        return getDeleted();
    }

    @Override
    public LocalDateTime component4() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime component5() {
        return getUpdatedAt();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public Boolean value3() {
        return getDeleted();
    }

    @Override
    public LocalDateTime value4() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime value5() {
        return getUpdatedAt();
    }

    @Override
    public MotorcadeRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public MotorcadeRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public MotorcadeRecord value3(Boolean value) {
        setDeleted(value);
        return this;
    }

    @Override
    public MotorcadeRecord value4(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public MotorcadeRecord value5(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public MotorcadeRecord values(Integer value1, String value2, Boolean value3, LocalDateTime value4, LocalDateTime value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MotorcadeRecord
     */
    public MotorcadeRecord() {
        super(Motorcade.MOTORCADE);
    }

    /**
     * Create a detached, initialised MotorcadeRecord
     */
    public MotorcadeRecord(Integer id, String name, Boolean deleted, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(Motorcade.MOTORCADE);

        set(0, id);
        set(1, name);
        set(2, deleted);
        set(3, createdAt);
        set(4, updatedAt);
    }
}
