/*
 * This file is generated by jOOQ.
 */
package cn.sl.manager.database;


import cn.sl.manager.database.tables.AccountCheckout;
import cn.sl.manager.database.tables.AccountRecord;
import cn.sl.manager.database.tables.Bank;
import cn.sl.manager.database.tables.Berth;
import cn.sl.manager.database.tables.BerthOrder;
import cn.sl.manager.database.tables.DiscountCoupon;
import cn.sl.manager.database.tables.Fee;
import cn.sl.manager.database.tables.FinanceBook;
import cn.sl.manager.database.tables.Goods;
import cn.sl.manager.database.tables.Motorcade;
import cn.sl.manager.database.tables.User;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sl extends SchemaImpl {

    private static final long serialVersionUID = -584416934;

    /**
     * The reference instance of <code>sl</code>
     */
    public static final Sl SL = new Sl();

    /**
     * The table <code>sl.account_checkout</code>.
     */
    public final AccountCheckout ACCOUNT_CHECKOUT = AccountCheckout.ACCOUNT_CHECKOUT;

    /**
     * The table <code>sl.account_record</code>.
     */
    public final AccountRecord ACCOUNT_RECORD = AccountRecord.ACCOUNT_RECORD;

    /**
     * The table <code>sl.bank</code>.
     */
    public final Bank BANK = Bank.BANK;

    /**
     * The table <code>sl.berth</code>.
     */
    public final Berth BERTH = Berth.BERTH;

    /**
     * The table <code>sl.berth_order</code>.
     */
    public final BerthOrder BERTH_ORDER = BerthOrder.BERTH_ORDER;

    /**
     * The table <code>sl.discount_coupon</code>.
     */
    public final DiscountCoupon DISCOUNT_COUPON = DiscountCoupon.DISCOUNT_COUPON;

    /**
     * The table <code>sl.fee</code>.
     */
    public final Fee FEE = Fee.FEE;

    /**
     * The table <code>sl.finance_book</code>.
     */
    public final FinanceBook FINANCE_BOOK = FinanceBook.FINANCE_BOOK;

    /**
     * The table <code>sl.goods</code>.
     */
    public final Goods GOODS = Goods.GOODS;

    /**
     * The table <code>sl.motorcade</code>.
     */
    public final Motorcade MOTORCADE = Motorcade.MOTORCADE;

    /**
     * The table <code>sl.user</code>.
     */
    public final User USER = User.USER;

    /**
     * No further instances allowed
     */
    private Sl() {
        super("sl", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            AccountCheckout.ACCOUNT_CHECKOUT,
            AccountRecord.ACCOUNT_RECORD,
            Bank.BANK,
            Berth.BERTH,
            BerthOrder.BERTH_ORDER,
            DiscountCoupon.DISCOUNT_COUPON,
            Fee.FEE,
            FinanceBook.FINANCE_BOOK,
            Goods.GOODS,
            Motorcade.MOTORCADE,
            User.USER);
    }
}
