/*
 * This file is generated by jOOQ.
 */
package cn.sl.manager.database;


import cn.sl.manager.database.tables.AccountCheckout;
import cn.sl.manager.database.tables.AccountRecord;
import cn.sl.manager.database.tables.Bank;
import cn.sl.manager.database.tables.Berth;
import cn.sl.manager.database.tables.BerthOrder;
import cn.sl.manager.database.tables.DiscountCoupon;
import cn.sl.manager.database.tables.Fee;
import cn.sl.manager.database.tables.FinanceBook;
import cn.sl.manager.database.tables.Goods;
import cn.sl.manager.database.tables.Motorcade;
import cn.sl.manager.database.tables.User;


/**
 * Convenience access to all tables in sl
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>sl.account_checkout</code>.
     */
    public static final AccountCheckout ACCOUNT_CHECKOUT = AccountCheckout.ACCOUNT_CHECKOUT;

    /**
     * The table <code>sl.account_record</code>.
     */
    public static final AccountRecord ACCOUNT_RECORD = AccountRecord.ACCOUNT_RECORD;

    /**
     * The table <code>sl.bank</code>.
     */
    public static final Bank BANK = Bank.BANK;

    /**
     * The table <code>sl.berth</code>.
     */
    public static final Berth BERTH = Berth.BERTH;

    /**
     * The table <code>sl.berth_order</code>.
     */
    public static final BerthOrder BERTH_ORDER = BerthOrder.BERTH_ORDER;

    /**
     * The table <code>sl.discount_coupon</code>.
     */
    public static final DiscountCoupon DISCOUNT_COUPON = DiscountCoupon.DISCOUNT_COUPON;

    /**
     * The table <code>sl.fee</code>.
     */
    public static final Fee FEE = Fee.FEE;

    /**
     * The table <code>sl.finance_book</code>.
     */
    public static final FinanceBook FINANCE_BOOK = FinanceBook.FINANCE_BOOK;

    /**
     * The table <code>sl.goods</code>.
     */
    public static final Goods GOODS = Goods.GOODS;

    /**
     * The table <code>sl.motorcade</code>.
     */
    public static final Motorcade MOTORCADE = Motorcade.MOTORCADE;

    /**
     * The table <code>sl.user</code>.
     */
    public static final User USER = User.USER;
}
